### PR TITLE
autoplay added to carousel + iic logo added to title+ color scheme changed

### PR DESCRIPTION
**Pull request by ayan-biswas0412**
* autoplay to favicon added for 3500 milsec one slide

### CODE REVIEW

**Comment by skshahnawaz** [comment]
The slider starts even before the picture gets loaded wholly. Also the logo is not fully appearing. Check once

Screenshot 2020-03-31 at 5 28 27 PM

**Comment by ayan-biswas0412** [comment]
Just refresh the page this would fix I think because I have seen this just for one time

**Comment by ayan-biswas0412** [comment]
I think by addition of a good preloader will resolve this

**Comment by ayan-biswas0412** [comment]
image
See the logo is in position and in mobile view also it is in position

**Comment by skshahnawaz** [comment]
great work indeed !

**Pull request merged**
